name: Add Period to README

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Port context information'
        required: false
        type: string

jobs:
  add-period:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use PAT instead of GITHUB_TOKEN to allow triggering other workflows
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Add period to README.md
        run: |
          # Append a period to the README.md file
          echo "." >> README.md
          
      - name: Commit and push changes
        run: |
          # Configure Git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit and push changes directly to master branch
          git add README.md
          git commit -m "Add period to README.md"
          git push origin master
                       

      - name: Update Port Run Status
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          status: "SUCCESS"
          logMessage: "Action completed successfully"
